### ISSUE TITLE
the root's cmakeList.txt is missing 

### ISSUE THREAD

**Issue by firebrain7** [ResearchDaniel/Correlated-Photon-Mapping-for-Interactive-Global-Illumination-of-Time-Varying-Volumetric-Data#2]
We need a root's cmakeList.txt to build the project.
Could you offer it?
thousand thanks.

**Comment by ResearchDaniel** [comment]
Hi @firebrain7, have you followed the build instructions in readme.md?

**Comment by firebrain7** [comment]
Hi Daniel @ResearchDaniel 
I followed it, and I am stuck at this part.
which is the source code path that I should set in Cmake？
![image](https://user-images.githubusercontent.com/16367644/67635667-65865a80-f904-11e9-8082-2fc94f74b2e7.png)
![image](https://user-images.githubusercontent.com/16367644/67635678-7cc54800-f904-11e9-96d2-68306c5fd6ce.png)
(This is the path I set, but it did not work)

**Comment by firebrain7** [comment]
Daniel, thanks 
I will check again

**Comment by firebrain7** [comment]
Hi Daniel @ResearchDaniel 
I have check the instructions, but some errors are occured when I compile the project. 
It's mainly about the uniformgridcl and radixsortcl part. Do you have the advice to pass through it?
By the way, the boost lib folder have been included in my pc's PATH, Is that ok?

below the two pages log of error 
![image](https://user-images.githubusercontent.com/16367644/68002769-683ad400-fca5-11e9-8691-33ea4be3c13e.png)
![image](https://user-images.githubusercontent.com/16367644/68002888-029b1780-fca6-11e9-854c-ba944f038c02.png)

**Comment by firebrain7** [comment]
my goal is to make a demo which using basic (without progressive or correlated) volumetric photon mappping method to render volume data, and set up my own thoughts on it. 
In order to reach this goal, I have read the Henrick's book about volumetric photon mapping method carefully and wrote down the pseudocode. However, I did not know how to transfer the pseudocode to the real code. 
So I try to find the solution on the internet, but I just found the photon mapping method for rendering participating media instead of volume data. Another trying route is to rebuild the current solution of paper for rendering the volume data using phton mapping,  and try to push it back to the basic version(without improvement) and set up my own thoughts. 
Do you have any advice how to achieve the goal?

**Comment by ResearchDaniel** [comment]
> Hi Daniel @ResearchDaniel
> I have check the instructions, but some errors are occured when I compile the project.
> It's mainly about the uniformgridcl and radixsortcl part. Do you have the advice to pass through it?

It looks like there might be some includes missing. The compiler might have become more strict since I compiled the source code a few years ago.
For example, undeclared identifier 'exportButton_' is probably due to missing include:
`#include <inviwo/core/properties/buttonproperty.h>`

Which version of Inviwo are you compiling 0.9.7? Otherwise, some errors might be due to changes in Inviwo.

> By the way, the boost lib folder have been included in my pc's PATH, Is that ok?

Yes, that should be ok.


> my goal is to make a demo which using basic (without progressive or correlated) volumetric photon mappping method to render volume data, and set up my own thoughts on it.
In order to reach this goal, I have read the Henrick's book about volumetric photon mapping method carefully and wrote down the pseudocode. However, I did not know how to transfer the pseudocode to the real code.
So I try to find the solution on the internet, but I just found the photon mapping method for rendering participating media instead of volume data. Another trying route is to rebuild the current solution of paper for rendering the volume data using phton mapping, and try to push it back to the basic version(without improvement) and set up my own thoughts.
Do you have any advice how to achieve the goal?

I think that using this code is a good way to achieve your goal since basically everything is there already. 
Just make sure that you are using the exact setup as described in the build setup first. Once you get it up and running you can upgrade your environment one by one to see where the errors might come from. Unfortunatelu, I currently do not have time to update the code but I might have some time in the future. What is your time-span for the project?

**Comment by firebrain7** [comment]
My time-span is about several months.
But I want to set up this project ASAP to experiment my thought. And the inviwo version is 0.9.7 whose source zip was downloaded directly from github.

**Comment by ResearchDaniel** [comment]
Ok, good. Which compiler/IDE are you using? Visual Studio 2019?

**Comment by firebrain7** [comment]
thanks,my software mainly envronment:
windows 10, visual studio 2017, qt 5.13

**Comment by ResearchDaniel** [comment]
Ok, I would not expect many errors except maybe the missing includes.

**Comment by firebrain7** [comment]
Hi Daniel
Through some work, i have fixed the error above! In my environment, the error is mainly caused because of not include some headers in part of cpp files. After include them , it's ok. thanks
![image](https://user-images.githubusercontent.com/16367644/68027447-58df7900-fced-11e9-9c92-60f86001910f.png)
![image](https://user-images.githubusercontent.com/16367644/68032961-b5e12c00-fcf9-11e9-8e76-962e89ed141d.png)
thanks a lot for the help. Then I will try to push it back to a basic method(without correlated and progressive improvement).

**Comment by ResearchDaniel** [comment]
Sweet!!! Would it possible for you to make a pull request with the changes you made?

**Comment by firebrain7** [comment]
Definitely, I will pull the request soon and you can test it on your environment when you have time.

**Comment by firebrain7** [comment]
request is pulled you could checked it when you have time.
thanks a lot, good night Daniel
